name: PD Test
on:
  push:
    branches:
      - master
      - release-4.0
      - release-5.*
      - release-6.*
      - release-7.*
      - release-8.*
  pull_request:
    branches:
      - master
      - release-4.0
      - release-5.*
      - release-6.*
      - release-7.*
      - release-8.*
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  chunks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - worker_id: 5
            name: 'Tests(2)'
    outputs:
      job-total: 1 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: ${{ matrix.name }}
        env:
          WORKER_ID: ${{ matrix.worker_id }}
        run: |
          make ci-test-job JOB_INDEX=$WORKER_ID
          mv covprofile covprofile_$WORKER_ID
          if [ -f junitfile ]; then
            cat junitfile
          fi
